### ISSUE TITLE
awk regexp on RHEL6

### ISSUE THREAD

**Issue by arnewiebalck** [luxflux/puppet-sysfs#3]
Hi,

The pattern matching in the awk command for RHEL based systems does not work on RHEL6 based systems which come with gawk version 3.1.7 where \S is not (yet?) supported yet it seems:

$ cat /tmp/xyz
a=b

$ awk -F= '/(\S+)\s*=(\S+)/{cmd=sprintf("echo %s > /sys/%s",$2, $1); print(cmd)}' /tmp/xyz
$
(empty!)

$ awk -F= '{cmd=sprintf("echo %s > /sys/%s",$2, $1); print(cmd)}' /tmp/xyz
echo b > /sys/a
(works!)

My attempts to fix that with [:space:] failed, so I am wondering what the point of that regexp is in the first place. I guess it is there to avoid white spaces in the path if the resource starts with a blank?
Couldn't the input be sanitized before the file is written?

Any other idea how to fix that?

Thanks!
 Arne

**Comment by nexecook** [comment]
https://github.com/luxflux/puppet-sysfs/pull/8 fixes the regex

**Comment by luxflux** [comment]
As I merged #8, I assume this problem has been fixed. Please reopen if not.
